# Generated by Django 3.2.7 on 2021-09-09 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.ImageField(default=0, upload_to='')),
                ('description', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='uplodedimages/')),
            ],
        ),
    ]
